/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as DistrictsRouteImport } from './routes/districts'
import { Route as BriefingRouteImport } from './routes/briefing'
import { Route as IndexRouteImport } from './routes/index'

const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const DistrictsRoute = DistrictsRouteImport.update({
  id: '/districts',
  path: '/districts',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingRoute = BriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/briefing': typeof BriefingRoute
  '/districts': typeof DistrictsRoute
  '/network': typeof NetworkRoute
  '/risk': typeof RiskRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/briefing': typeof BriefingRoute
  '/districts': typeof DistrictsRoute
  '/network': typeof NetworkRoute
  '/risk': typeof RiskRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/briefing': typeof BriefingRoute
  '/districts': typeof DistrictsRoute
  '/network': typeof NetworkRoute
  '/risk': typeof RiskRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/briefing' | '/districts' | '/network' | '/risk'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/briefing' | '/districts' | '/network' | '/risk'
  id: '__root__' | '/' | '/briefing' | '/districts' | '/network' | '/risk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BriefingRoute: typeof BriefingRoute
  DistrictsRoute: typeof DistrictsRoute
  NetworkRoute: typeof NetworkRoute
  RiskRoute: typeof RiskRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/districts': {
      id: '/districts'
      path: '/districts'
      fullPath: '/districts'
      preLoaderRoute: typeof DistrictsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing': {
      id: '/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof BriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BriefingRoute: BriefingRoute,
  DistrictsRoute: DistrictsRoute,
  NetworkRoute: NetworkRoute,
  RiskRoute: RiskRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
